# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Indy Beck
title: Technologist, Architect, Engineer, 
email: indy.w.beck@gmail.com
website: https://indybeck.github.io/indybeck/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  indybeck
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: indybeck
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: DyausLab
  icon: fas fa-globe
  url: https://dyauslab.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Indy. As a passionate Technologist and Engineer, I take immense pride in my multifaceted roles: a devoted Father and, most importantly, a compassionate advocate for human betterment. My driving force lies in fostering a world where empathy and benevolence are ingrained in our interactions. I firmly believe that by leveraging our collective knowledge, we can empower others to embrace kindness and create a positive impact on each other's lives. Through my work and dedication, I aspire to lead by example and instill the values of learning, understanding, and supporting one another, all while striving for excellence in everything we do as a society.
  
content:
  - title: Passionate about ...
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am fervently devoted to helping individuals and businesses harness the power of AI technology to overcome challenges and drive positive change. My core passions include:
      - Empowering people to adapt AI technology effectively to solve complex problems.
      - Guiding and educating individuals on how AI technology can be leveraged to enhance processes and achieve their goals.
      - Devising and implementing appropriate and innovative technological solutions and architectures to address specific issues.
      - Assisting organizations in streamlining and optimizing their AI projects, ensuring seamless integration into their existing operations.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: To be updated
        # link: github.com/sproogen
        # # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        #   # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   #   icon: fab fa-github
        #   #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
        #   I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DyausLab
        link: https://dyauslab.github.io/
        sub_title: Founder
        caption: 2023-Present
        quote: >
          my passion
        description: | # this will include new lines to allow paragraphs
          exploring and discussing with creative minds in following area:
          - Manutacturing
          - Agriculture (Hydrophonics and AI, as an example)
          - Healthcare automation
          - DevOps and MLops & automation using AI
      - layout: left
        title: Exponential AI
        link: https://exponentialai.com/
        sub_title: Cheif Architect
        caption: 2018-Present
        quote: >
          Cheif Architect
        description: | # this will include new lines to allow paragraphs
          Architect, DevOps, MLops, Successful deliveries to some of our awesome clients and partners:
          - Anthem(aka Carelon)
          - PwC
          - Deloitte
          - Merck
          - Sanofi
      - layout: left
        title: Previous startups
        link: 
        sub_title: Software Engineer, Leader
        caption: 2013-2017
        quote: >
          helped to grow following startups
        description: | # this will include new lines to allow paragraphs
          - Cognitive Scale: Principal software engineer, my first startup, founding member(No 3)
          - Session M: Technical Director, DevOps innovation
          - Swoop: Princial software enginer
          - IPM.ai: Cloud, technology advisor to founding members
      - layout: left
        title: IBM Software
        link: ibm.com
        # link_text: boringcompany.com
        sub_title: Lotus, Tivoli, WebSphere, DB2, and more
        caption: 1999 - 2013
        quote: >
          Software engineer, leader, contributor, architect, devOps, virtualization and provisioning 
        description: | # this will include new lines to allow paragraphs
          14 passionate years of contribution to IBM; some of the highlights
          - IBM Watson
          - IBM SWG virtualization and provisioning projects, Green initiatives
          - Lotus Domino Product support L2, L3, Lotus Engineering Team
          - Technical Sales Engineer and lived in Singapore
  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      Masters and Bachelor at Compuster Science and Engineering. Attended at
      - UBC
      - Dongguk Univ
  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technology, I enjoy :
      - Running(5k ~ 10 miles)
      - Workout at The Weight room
      - skiing, surfing, jetskiing (no expert, just enjoying)
      - learning piano from my daughters

      And, a cool pic from Whister:  
      ![whister1](/images/img_1142.jpeg "whister1")
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
